/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer.CustomerDirectory;
import Business.FlightSchedule.Flight;
import Business.FlightSchedule.FlightSchedule;
import java.awt.CardLayout;
import java.awt.List;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JPanel;

/**
 *
 * @author bb
 */
public class SearchBestFlights extends javax.swing.JPanel {

    /**
     * Creates new form SearchBestFlight
     */
    private JPanel rightPanel;
    private FlightSchedule flightSchedule;
    private CustomerDirectory cusDir;
    
    public SearchBestFlights(JPanel rightPanel, FlightSchedule flightSchedule,CustomerDirectory cusDir) {
        initComponents();
        this.rightPanel = rightPanel;
        this.flightSchedule = flightSchedule;
        this.cusDir=cusDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbtnMorning = new javax.swing.JRadioButton();
        rbtnDayTime = new javax.swing.JRadioButton();
        rbtnEvening = new javax.swing.JRadioButton();
        tfFlightNum = new javax.swing.JTextField();
        tfDepartL = new javax.swing.JTextField();
        tfArrivalL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("PMingLiU", 1, 24)); // NOI18N
        jLabel1.setText("Search Best Flights");

        jLabel2.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        jLabel2.setText("Flight Number : ");

        jLabel3.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        jLabel3.setText("Departure Location :");

        jLabel4.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        jLabel4.setText("Arrival Location :");

        jLabel5.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        jLabel5.setText("Preferred Time Of Day :");

        buttonGroup1.add(rbtnMorning);
        rbtnMorning.setText("Morning");

        buttonGroup1.add(rbtnDayTime);
        rbtnDayTime.setText("Day Time");

        buttonGroup1.add(rbtnEvening);
        rbtnEvening.setText("Evening");

        jLabel6.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        jLabel6.setText("Date :");

        btnSearch.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        btnSearch.setText("SEARCH>>");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("PMingLiU", 0, 18)); // NOI18N
        jButton1.setText(">>Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbtnDayTime)
                                    .addComponent(rbtnMorning)
                                    .addComponent(rbtnEvening)
                                    .addComponent(tfFlightNum)
                                    .addComponent(tfDepartL)
                                    .addComponent(tfArrivalL)
                                    .addComponent(tfDate, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfFlightNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDepartL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfArrivalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtnMorning))
                .addGap(18, 18, 18)
                .addComponent(rbtnDayTime)
                .addGap(18, 18, 18)
                .addComponent(rbtnEvening)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(jButton1))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        ArrayList[] result = new ArrayList[5];
        for(int i = 0; i < result.length; i++){
            result[i] = new ArrayList();
        }
        
        String flightNum = tfFlightNum.getText();
        if(flightNum == null || flightNum.equals("")){
            result[0].addAll(flightSchedule.getFlightList());
        }else{
            result[0].addAll(flightSchedule.searchFlightNum(flightNum));
        }
        
        String departureL = tfDepartL.getText();
        if(departureL == null || departureL.equals("")){
            result[1].addAll(flightSchedule.getFlightList());
        }else{
            result[1].addAll(flightSchedule.searchDepartureLocation(departureL));
        }
        
        String arrivalL = tfArrivalL.getText();
        if(arrivalL == null || arrivalL.equals("")){
            result[2].addAll(flightSchedule.getFlightList());
        }else{
            result[2].addAll(flightSchedule.searchArrivalLocation(arrivalL));
        }
        
        if(!rbtnMorning.isSelected() && !rbtnDayTime.isSelected() && !rbtnEvening.isSelected()){
            result[3].addAll(flightSchedule.getFlightList());
        }else{
            String dayOfTime = "morning";
            if(rbtnMorning.isSelected()){
                dayOfTime = "morning";
            }else if(rbtnDayTime.isSelected()){
                dayOfTime = "daytime";
            }else{
                dayOfTime = "evening";
            }
            result[3].addAll(flightSchedule.searchTimeOfDay(dayOfTime));
        }
        
        String Date = tfDate.getText();
        if(Date == null || Date.equals("")){
            result[4].addAll(flightSchedule.getFlightList());
        }else{
            result[4].addAll(flightSchedule.searchDate(Date));
        }
        
        for(int i =0; i<4; i++){
            result[i+1].retainAll(result[i]);
        }
        
        SearchResult pane =new SearchResult(rightPanel,result[4],cusDir,flightSchedule);
        rightPanel.add("SearchResult",pane);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
      
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.rightPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbtnDayTime;
    private javax.swing.JRadioButton rbtnEvening;
    private javax.swing.JRadioButton rbtnMorning;
    private javax.swing.JTextField tfArrivalL;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfDepartL;
    private javax.swing.JTextField tfFlightNum;
    // End of variables declaration//GEN-END:variables
}
