/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DietitionRole;

//import Business.WorkQueue.ClientTestWorkRequest;
import Business.Client.Client;
import Business.Food.FoodDirectory;
import Business.WorkQueue.DietitionTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.ChooseFoodJFrame;
import userinterface.ViewClient;

/**
 *
 * @author raunak
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    DietitionTestWorkRequest request;
    private FoodDirectory foodDirectory;
    

    ProcessWorkRequestJPanel(JPanel userProcessContainer, DietitionTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        foodDirectory = new FoodDirectory();
        ClientName.setText(String.valueOf(request.getSender()));
        FoodList.setText(request.getFoodList().toString());
//        Disease.setText(request.getClientList().toString());
        
    }
    /**
     * Creates new form ProcessWorkRequestJPanel
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecipeChoice = new javax.swing.ButtonGroup();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        Accept = new javax.swing.JRadioButton();
        Refuse = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        ClientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FoodList = new javax.swing.JTextField();
        choosereciept = new javax.swing.JButton();
        Foodl = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        ViewDetails = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        submitJButton.setBackground(new java.awt.Color(255, 255, 255));
        submitJButton.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(440, 280, 200, 60);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Result");
        add(jLabel1);
        jLabel1.setBounds(120, 180, 80, 40);

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(120, 280, 110, 60);

        RecipeChoice.add(Accept);
        Accept.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        Accept.setText("Accept");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });
        add(Accept);
        Accept.setBounds(240, 190, 110, 30);

        RecipeChoice.add(Refuse);
        Refuse.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        Refuse.setText("Refuse");
        add(Refuse);
        Refuse.setBounds(370, 190, 100, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Client Name");
        add(jLabel2);
        jLabel2.setBounds(119, 66, 110, 20);

        ClientName.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        add(ClientName);
        ClientName.setBounds(247, 61, 154, 40);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Food");
        add(jLabel3);
        jLabel3.setBounds(120, 130, 80, 30);

        FoodList.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        add(FoodList);
        FoodList.setBounds(250, 130, 150, 40);

        choosereciept.setBackground(new java.awt.Color(255, 255, 255));
        choosereciept.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        choosereciept.setText("Choose");
        choosereciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserecieptActionPerformed(evt);
            }
        });
        add(choosereciept);
        choosereciept.setBounds(490, 190, 97, 29);

        Foodl.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        add(Foodl);
        Foodl.setBounds(250, 220, 183, 40);

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        add(refresh);
        refresh.setBounds(490, 219, 100, 40);

        ViewDetails.setText("View Details");
        ViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsActionPerformed(evt);
            }
        });
        add(ViewDetails);
        ViewDetails.setBounds(420, 59, 121, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DietitionRole/dribbbe_dietitian-01.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DietitionWorkAreaJPanel dwjp = (DietitionWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        if(Accept.isSelected()){
            request.setTestResult("Accept");
            request.setStatus("DietitionCompleted");
            JOptionPane.showMessageDialog(null, "Accept");
        }else if(Refuse.isSelected()){
            request.setTestResult("Dietitan Refused and Changed");
            request.setStatus("DietitionCompleted");
            JOptionPane.showMessageDialog(null, "Dietitan Refused and Changed");
        }else{
            JOptionPane.showMessageDialog(null, "please choose one recipe");
            return;
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptActionPerformed

    private void chooserecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserecieptActionPerformed
        // TODO add your handling code here:
        if(Refuse.isSelected()){
            ChooseFoodJFrame e = new ChooseFoodJFrame(foodDirectory);
            e.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "please select Need Dietitian");
        }

    }//GEN-LAST:event_chooserecieptActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        //        System.out.print(foodDirectory.toString());
        Foodl.setText(String.valueOf(foodDirectory.getFoodList().toString()));
        request.setFoodList(foodDirectory.getFoodList());
//        request.setTestResult("Dietitan Refused and Changed");
    }//GEN-LAST:event_refreshActionPerformed

    private void ViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsActionPerformed
        // TODO add your handling code here:
        for(Client client: request.getClientDirectory().getClientList()){
            if(client.getClientName().equals(request.getSender().getUsername())){
                //                System.out.print(client.getAge());
                ViewClient view = new ViewClient(client);
                view.setVisible(true);
            }
        }

    }//GEN-LAST:event_ViewDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Accept;
    private javax.swing.JTextField ClientName;
    private javax.swing.JTextField FoodList;
    private javax.swing.JTextField Foodl;
    private javax.swing.ButtonGroup RecipeChoice;
    private javax.swing.JRadioButton Refuse;
    private javax.swing.JButton ViewDetails;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton choosereciept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton refresh;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
