/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.dior.CSR;

import Business.Employee.Employee;
import Business.Enterprise.BeautyEnterprise;
import Business.Organization.CSROrganization;
import Business.Organization.Organization;
import Business.Organization.CustomerOrganization;
import Business.Organization.SupplierAdminOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MessageReplyRequest;
import Business.WorkQueue.MessageSendRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wuxinyang
 */
public class replyMessageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form replyMessageJPanel
     */
    
     private JPanel userProcessContainer;
       private BeautyEnterprise benterprise;
       private MessageSendRequest wr;
       private MessageReplyRequest mrp;
    replyMessageJPanel(JPanel userProcessContainer, BeautyEnterprise enterprise, WorkRequest wr, WorkRequest mrp) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.benterprise = (BeautyEnterprise)enterprise;
        this.wr=(MessageSendRequest)wr;
        this.mrp=(MessageReplyRequest)mrp;
        
        for(Organization org :benterprise.getOrganizationDirectory().getOrganizationList()){
             if (org instanceof CSROrganization){
            for(Employee em : org.getEmployeeDirectory().getEmployeeList()){
                em.getName();
           nameTxt.setText(em.getName());
            }
             } 
        }
        orderId.setText(String.valueOf(((MessageSendRequest)wr).getOrderId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Message(*):");

        nameTxt.setEditable(false);

        jLabel1.setText("CSR Name: ");

        jLabel2.setText("Order ID:");

        orderId.setEditable(false);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Reply Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameTxt)
                                        .addComponent(orderId, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(430, 430, 430)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(orderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(jTextArea1.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please write the message!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
//         if(wr.getSendStatus().equals("replyed")){
//             JOptionPane.showMessageDialog(null, "Already reply!","Warning",JOptionPane.WARNING_MESSAGE);
//            return;
//         }
        
        mrp.setReplyMessage(jTextArea1.getText());
        mrp.setOrderId(Integer.parseInt(orderId.getText()));
        mrp.setCSRName(nameTxt.getText());
        
        mrp.setCustomerName(wr.getCustomerName());
       // System.out.println(mrp.getCustomerName());
        mrp.setReplyStatus("replyed");
        wr.setSendStatus("replyed");
        
        
//        benterprise.getWorkQueue().getWorkRequestList().add(mrp);
        
                for(UserAccount ua:benterprise.getUserAccountDirectory().getUserAccountList()){
                    ua.getWorkQueue().getWorkRequestList().add(mrp);
                }
        
        Organization org = null;  
            for (Organization organization : benterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof CustomerOrganization){
                org = organization;
                break; 
                }
            }
          //  System.out.println(org);
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(mrp);
                
                for(UserAccount ua:benterprise.getUserAccountDirectory().getUserAccountList()){
                    ua.getWorkQueue().getWorkRequestList().add(mrp);
                }
                
            }
            
            JOptionPane.showMessageDialog(null, "Message send successfully");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        Component[] comps = userProcessContainer.getComponents();
        layout.previous(userProcessContainer);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField orderId;
    // End of variables declaration//GEN-END:variables
}
