/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.customer;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.BeautyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wuxinyang
 */
public class UpdateInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateInfoJPanel
     */
    
    
    
   

        private JPanel userProcessContainer;
        private UserAccount account;
        private EcoSystem business;
    UpdateInfoJPanel(JPanel userProcessContainer, BeautyEnterprise benterprise, UserAccount account, CustomerOrganization corganization, EcoSystem business) {
       initComponents();
       this.userProcessContainer= userProcessContainer;
       this.account= account;
       this.business=business;
        txtlName.setText(account.getCustomer().getLname());        
        txtfName.setText(account.getCustomer().getFname());
        txtAddress.setText(account.getCustomer().getAddress());
        txtEmail.setText(account.getCustomer().getEmail());
        txtPhonenum.setText(account.getCustomer().getPhoneNum());
        txtBankaccount.setText(account.getCustomer().getBankAccountNum());
        txtBirth.setText(String.valueOf(account.getCustomer().getBirth()));
      //  imageLabel.setIcon(account.getCustomer().getPicture());
        genderComboBox.setSelectedItem(String.valueOf(account.getCustomer().getGender()));
        monthComboBox.setSelectedItem(String.valueOf(account.getCustomer().getMonthlyC()));
        ImageIcon icon=new ImageIcon(account.getCustomer().getPath());
        icon.setImage(icon.getImage().getScaledInstance(120,130,Image.SCALE_DEFAULT));
        imageLabel.setIcon(icon);
        
        txtlName.setEditable(false);
        txtfName.setEditable(false);
        txtAddress.setEditable(false);
        txtEmail.setEditable(false);
        txtPhonenum.setEditable(false);
        txtBankaccount.setEditable(false);
        txtBirth.setEditable(false);
        genderComboBox.setEnabled(false);
        monthComboBox.setEnabled(false);
        saveBtn.setEnabled(false);
        updBtn.setEnabled(true);
        jButton3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhonenum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBankaccount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfName = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtlName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        imagepathTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setText("Back Account:");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Update Info");

        jLabel2.setText("First Name:");

        jLabel3.setText("Address:");

        jLabel7.setText("Date of Brith:");

        txtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNameActionPerformed(evt);
            }
        });

        jLabel8.setText("Last Name:");

        txtlName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        jLabel5.setText("Phone Num:");

        saveBtn.setBackground(new java.awt.Color(255, 204, 204));
        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updBtn.setBackground(new java.awt.Color(255, 204, 204));
        updBtn.setText("Update");
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        genderComboBox.setBackground(new java.awt.Color(255, 204, 204));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "female", "male", "secret" }));

        jLabel14.setText("Gender：");

        jLabel15.setText("Monthly consumption：");

        monthComboBox.setBackground(new java.awt.Color(255, 204, 204));
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500-1000", "1000-2000", "2000-3000", "3000-4000", "4000-5000", ">5000" }));

        jDateChooser1.setBackground(new java.awt.Color(255, 204, 204));
        jDateChooser1.setEnabled(false);

        jButton2.setText("<=");
        jButton2.setEnabled(false);
        jButton2.setFocusCycleRoot(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        imageLabel.setText("Personal Picture");
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        imagepathTextField.setEditable(false);
        imagepathTextField.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        imagepathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagepathTextFieldActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton3.setText("Attach");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(363, 363, 363)
                                .addComponent(updBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtlName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtPhonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtBankaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(imagepathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(monthComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(641, 641, 641))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagepathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhonenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBankaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNameActionPerformed

    private void txtlNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlNameActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        txtlName.setEditable(false);
        txtfName.setEditable(false);
        txtAddress.setEditable(false);
        txtEmail.setEditable(false);
        txtPhonenum.setEditable(false);
        txtBankaccount.setEditable(false);
        txtBirth.setEditable(false);
        genderComboBox.setEnabled(false);
        monthComboBox.setEnabled(false);
        jButton3.setEnabled(false);
        saveBtn.setEnabled(false);
        jDateChooser1.setEnabled(false);
        jButton2.setEnabled(false);
        updBtn.setEnabled(true);

        if(txtfName.getText().isEmpty() ||txtlName.getText().isEmpty() ||txtAddress.getText().isEmpty() || txtEmail.getText().isEmpty()||txtPhonenum.getText().isEmpty()||txtBankaccount.getText().isEmpty()||txtBirth.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please add all the mendatory fields!","Warning",JOptionPane.WARNING_MESSAGE);
            txtlName.setEditable(true);
            txtfName.setEditable(true);
            txtAddress.setEditable(true);
            txtEmail.setEditable(true);
            txtPhonenum.setEditable(true);
            txtBankaccount.setEditable(true);
            txtBirth.setEditable(true);
            genderComboBox.setEnabled(true);
            monthComboBox.setEnabled(true);
            jDateChooser1.setEnabled(true);
            jButton3.setEnabled(true);
           jButton2.setEnabled(true);
            saveBtn.setEnabled(true);
            updBtn.setEnabled(false);
            return;

        }else{
            if(!userEmailPatternCorrect()){
                JOptionPane.showMessageDialog(null, "Please enter right email format!","Warning",JOptionPane.WARNING_MESSAGE);

                txtlName.setEditable(true);
                txtfName.setEditable(true);
                txtAddress.setEditable(true);
                txtEmail.setEditable(true);
                txtPhonenum.setEditable(true);
                txtBankaccount.setEditable(true);
                txtBirth.setEditable(true);
                genderComboBox.setEnabled(true);
                monthComboBox.setEnabled(true);
                jDateChooser1.setEnabled(true);
                jButton3.setEnabled(true);
                jButton2.setEnabled(true);
                saveBtn.setEnabled(true);
                updBtn.setEnabled(false);
                return;
            }
        }
        Date date;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse(txtBirth.getText());

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter right date format!","Warning",JOptionPane.WARNING_MESSAGE);

            txtlName.setEditable(true);
            txtfName.setEditable(true);
            txtAddress.setEditable(true);
            txtEmail.setEditable(true);
            txtPhonenum.setEditable(true);
            txtBankaccount.setEditable(true);
            txtBirth.setEditable(true);
            genderComboBox.setEnabled(true);
            monthComboBox.setEnabled(true);
            jDateChooser1.setEnabled(true);
            jButton3.setEnabled(true);
            jButton2.setEnabled(true);
            saveBtn.setEnabled(true);
            updBtn.setEnabled(false);
            return;
        }

        
       
        account.getCustomer().setFname(txtfName.getText());
        account.getCustomer().setLname(txtlName.getText());
        account.getCustomer().setAddress(txtAddress.getText());
        account.getCustomer().setEmail(txtEmail.getText());
        account.getCustomer().setPhoneNum(txtPhonenum.getText());
        account.getCustomer().setBirth(date);
        account.getCustomer().setBankAccountNum(txtBankaccount.getText());
        account.getCustomer().setPicture(imageLabel.getIcon());
        account.getCustomer().setPath(imagepathTextField.getText());

        JOptionPane.showMessageDialog(null, "Update Successfully");

    }//GEN-LAST:event_saveBtnActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed
        // TODO add your handling code here:
        txtlName.setEditable(true);
        txtfName.setEditable(true);
        txtAddress.setEditable(true);
        txtEmail.setEditable(true);
        txtPhonenum.setEditable(true);
        txtBankaccount.setEditable(true);
        txtBirth.setEditable(true);
        genderComboBox.setEnabled(true);
        monthComboBox.setEnabled(true);
        jButton3.setEnabled(true);
        updBtn.setEnabled(false);
        saveBtn.setEnabled(true);
        jDateChooser1.setEnabled(true);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_updBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//         userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
        backAction();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy",Locale.getDefault());
        String d = sdf.format(jDateChooser1.getDate());
        txtBirth.setText(d);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void imagepathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagepathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagepathTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser =new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        imagepathTextField.setText(filename);

        ImageIcon icon=new ImageIcon(filename);

        icon.setImage(icon.getImage().getScaledInstance(120,130,Image.SCALE_DEFAULT));
        imageLabel.setIcon(icon);
    }//GEN-LAST:event_jButton3ActionPerformed
private boolean userEmailPatternCorrect(){
        String usernamePattern = "^[a-zA-Z0-9][a-zA-Z0-9_.]*@[a-zA-Z0-9]+\\.[a-zA-Z0-9]+";
        
        boolean c = Pattern.matches(usernamePattern, txtEmail.getText());
        if(c == true){
            System.out.print("This is a valid email ID");
            return true;
        }
        else{
            System.out.print("This is an invalid email ID");
            return false;
        }
    }


private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        customerWorkArea cwa = (customerWorkArea) component;
        cwa.ImageView();
//        ojp.populateOrderTable();
//        ojp.populateDelete();
//        ojp.populateReminder();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imagepathTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankaccount;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhonenum;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtlName;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables
}
