/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClientRole;

import Business.Client.ClientDirectory;
import userinterface.ChooseFoodJFrame;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Food.FoodDirectory;
import Business.Organization.DietitianOrganization;
import Business.Organization.Organization;
import Business.Organization.SenatealarmOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DietitionTestWorkRequest;
import Business.WorkQueue.HalarmTestWorkRequest;
import Business.WorkQueue.SenateTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RequestDietitionAdminOrSenateAdminTestJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private FoodDirectory foodDirectory;
    private ClientDirectory clientD;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestDietitionAdminOrSenateAdminTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,ClientDirectory clientD) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        foodDirectory = new FoodDirectory();
        valueLabel.setText(enterprise.getName());
        this.clientD=clientD;
//        System.out.println(enterprise.getFoodDirectory().getFoodList());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        NeedSenatealarm = new javax.swing.JRadioButton();
        NeedDietition = new javax.swing.JRadioButton();
        choosereciept = new javax.swing.JButton();
        FoodList = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 270, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 80, 30));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 110, 50));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, 30));

        buttonGroup1.add(NeedSenatealarm);
        NeedSenatealarm.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        NeedSenatealarm.setText("Need senateAlarm");
        NeedSenatealarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeedSenatealarmActionPerformed(evt);
            }
        });
        add(NeedSenatealarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        buttonGroup1.add(NeedDietition);
        NeedDietition.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        NeedDietition.setText("Need Dietitian");
        NeedDietition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeedDietitionActionPerformed(evt);
            }
        });
        add(NeedDietition, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        choosereciept.setBackground(new java.awt.Color(255, 255, 255));
        choosereciept.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        choosereciept.setText("Choose");
        choosereciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserecieptActionPerformed(evt);
            }
        });
        add(choosereciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 49, 100, 40));

        FoodList.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        FoodList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodListActionPerformed(evt);
            }
        });
        add(FoodList, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 240, 40));

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ClientRole/054101015DBD7CD7B09CD08E819D4223.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        String dmessage = "need dietitian";
        
        DietitionTestWorkRequest drequest = new DietitionTestWorkRequest();
        drequest.setClientDirectory(clientD);
        drequest.setMessage(dmessage);
        drequest.setSender(userAccount);
        drequest.setFoodList(foodDirectory.getFoodList());
        drequest.setStatus("Sent to dietition");
//        System.out.println(drequest.getClientDirectory().getClientList().toString());
        
        String smessage = "need nurse";
        HalarmTestWorkRequest srequest = new HalarmTestWorkRequest();
        srequest.setMessage(smessage);
        srequest.setSender(userAccount);
        srequest.setStatus("Sent senatealarm");
        Organization org = null;
        if(NeedDietition.isSelected()){
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof DietitianOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(drequest);
                userAccount.getWorkQueue().getWorkRequestList().add(drequest);
//                System.out.println(userAccount.getWorkQueue().getWorkRequestList().add(drequest));
            }
        }else if(NeedSenatealarm.isSelected()){
            System.out.println(smessage);
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof SenatealarmOrganization){
                    org = organization;
                    break;
                }
            }
            System.out.println(org);
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(srequest);
                userAccount.getWorkQueue().getWorkRequestList().add(srequest);
//                System.out.println(userAccount.getWorkQueue().getWorkRequestList().add(srequest));
            }
        }else{
            JOptionPane.showMessageDialog(null, "please select one service");
            return;
        }  
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClientWorkAreaJPanel dwjp = (ClientWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void NeedSenatealarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeedSenatealarmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeedSenatealarmActionPerformed

    private void NeedDietitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeedDietitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeedDietitionActionPerformed

    private void chooserecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserecieptActionPerformed
        // TODO add your handling code here:
        if(NeedDietition.isSelected()){
            ChooseFoodJFrame e = new ChooseFoodJFrame(foodDirectory);
            e.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "please select Need Dietitian");
        }
        
    }//GEN-LAST:event_chooserecieptActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
//        System.out.print(foodDirectory.toString());
       FoodList.setText(String.valueOf(foodDirectory.getFoodList().toString()));
    }//GEN-LAST:event_refreshActionPerformed

    private void FoodListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FoodList;
    private javax.swing.JRadioButton NeedDietition;
    private javax.swing.JRadioButton NeedSenatealarm;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton choosereciept;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton refresh;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
