/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Client.Client;
import Business.Client.ClientDirectory;
import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Food.FoodDirectory;
import java.awt.Color;
import static java.awt.Color.white;
import userinterface.ClientRole.RequestDietitionAdminOrSenateAdminTestJPanel;
import java.io.File;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leslie
 */
public class AddClient extends javax.swing.JFrame {

    
    private Enterprise enterprise;
    private ClientDirectory clientDirectory;
    
    /**
     * Creates new form SendEmailJFrame
     */
    
    public AddClient(ClientDirectory clientD) {
        initComponents();
//        enterprise = enterprise;
         this.clientDirectory =  clientD;
         popDieaseJComboBox();
       
    }
    
    public void popDieaseJComboBox() {
        setSize(900,600);
        setBackground(white);
        DieaseJComboBox.removeAllItems();
        String[] diease = {"No diease","heart diease","Lung cancer","Brain cancer","fracture"};
        for (String d: diease)  {
            DieaseJComboBox.addItem(d);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();

        model.setRowCount(0);
            for (Client cl: clientDirectory.getClientList()) {
                Object row[] = new Object[6];
                row[0] = cl.getClientName();
                row[1] = cl.getAge();
                row[2] = cl.getHeight();
                row[3] = cl.getWeight();
                row[4] = cl.getBloodPressure();
                row[5] = cl.getDieaseName(); 
                ((DefaultTableModel) userJTable.getModel()).addRow(row);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Height = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BloodPressure = new javax.swing.JTextField();
        ClientName = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Weight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DieaseJComboBox = new javax.swing.JComboBox();
        createUserJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(100, 230, 900, 600));
        getContentPane().setLayout(null);
        getContentPane().add(Height);
        Height.setBounds(140, 120, 141, 40);

        jLabel10.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel10.setText("Client Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 30, 120, 30);

        jLabel6.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel6.setText("Height");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 100, 80, 30);

        jLabel9.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel9.setText("Blood pressure");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 160, 150, 40);

        BloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPressureActionPerformed(evt);
            }
        });
        getContentPane().add(BloodPressure);
        BloodPressure.setBounds(120, 200, 141, 40);

        ClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientNameActionPerformed(evt);
            }
        });
        getContentPane().add(ClientName);
        ClientName.setBounds(161, 50, 150, 40);

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        getContentPane().add(Age);
        Age.setBounds(680, 50, 146, 40);

        jLabel7.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel7.setText("Weight");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(610, 100, 90, 40);

        Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightActionPerformed(evt);
            }
        });
        getContentPane().add(Weight);
        Weight.setBounds(690, 120, 146, 40);

        jLabel8.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel8.setText("Age");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(610, 30, 50, 40);

        jLabel11.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel11.setText("Diease");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(640, 160, 70, 40);

        DieaseJComboBox.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        DieaseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(DieaseJComboBox);
        DieaseJComboBox.setBounds(700, 200, 146, 40);

        createUserJButton.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        createUserJButton.setForeground(new java.awt.Color(102, 102, 255));
        createUserJButton.setText("Create");
        createUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createUserJButton);
        createUserJButton.setBounds(720, 270, 120, 50);

        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client Name", "Age", "Height", "Weight", "Blood Pressure", "Diease"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userJTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 350, 563, 179);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/kissclipart-nursing-ratchaburi-hospital-nurse-35d267551b6948e5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPressureActionPerformed

    private void ClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientNameActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightActionPerformed

    private void createUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButtonActionPerformed
        if(ClientName.getText()==null||ClientName.getText().equals("")){
            ClientName.setBorder(BorderFactory.createLineBorder(Color.red));
            jLabel10.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "ClientName can not be empty");
            return;
        }
        if(Age.getText()==null||Age.getText().equals("")){
            Age.setBorder(BorderFactory.createLineBorder(Color.red));
            jLabel8.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Age can not be empty");
            return;
        }
        if(BloodPressure.getText()==null||BloodPressure.getText().equals("")){
            BloodPressure.setBorder(BorderFactory.createLineBorder(Color.red));
            jLabel9.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "BloodPressure can not be empty");
            return;
        }
        if(Height.getText()==null||Height.getText().equals("")){
            Height.setBorder(BorderFactory.createLineBorder(Color.red));
            jLabel6.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Height can not be empty");
            return;
        }
        if(Weight.getText()==null||Weight.getText().equals("")){
            Weight.setBorder(BorderFactory.createLineBorder(Color.red));
            jLabel7.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Weight can not be empty");
            return;
        }

        try{
            Integer.parseInt(Age.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for Age");
            return;
        }
        try{
            Integer.parseInt(BloodPressure.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for BloodPressure");
            return;
        }
        try{
            Integer.parseInt(Height.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for Height");
            return;
        }
        try{
            Integer.parseInt(Weight.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for Weight");
            return;
        }
        
        Client client = new Client();
        client.setClientName(ClientName.getText());
        client.setAge(Integer.valueOf(Age.getText()));
        client.setBloodPressure(Integer.valueOf(BloodPressure.getText()));
        client.setDieaseName(String.valueOf(DieaseJComboBox.getSelectedItem()));
        client.setHeight(Integer.valueOf(Height.getText()));
        client.setWeight(Integer.valueOf(Weight.getText()));
        clientDirectory.addClient(client);
//        clientDirectory.createClient(ClientName.getText(), Integer.valueOf(Age.getText()), Integer.valueOf(BloodPressure.getText()), String.valueOf(DieaseJComboBox.getSelectedItem()), Integer.valueOf(Height.getText()), Integer.valueOf(Weight.getText()));
//        System.out.print(clientDirectory.getClientList().toString());

        JOptionPane.showMessageDialog(null, "Account created successfully");
        popData();
    }//GEN-LAST:event_createUserJButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField BloodPressure;
    private javax.swing.JTextField ClientName;
    private javax.swing.JComboBox DieaseJComboBox;
    private javax.swing.JTextField Height;
    private javax.swing.JTextField Weight;
    private javax.swing.JButton createUserJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables
}
