/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Food.FoodDirectory;
import userinterface.ClientRole.RequestDietitionAdminOrSenateAdminTestJPanel;
import java.io.File;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author leslie
 */
public class ChooseFoodJFrame extends javax.swing.JFrame {

    
    private Enterprise enterprise;
    private FoodDirectory foodDirectory;
    
    /**
     * Creates new form SendEmailJFrame
     */
    
    public ChooseFoodJFrame(FoodDirectory foodDirectory) {
        
        initComponents();
        setSize(900,600);
//        enterprise = enterprise;
         this.foodDirectory =  foodDirectory;
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fish = new javax.swing.JRadioButton();
        Potato = new javax.swing.JRadioButton();
        Broccoli = new javax.swing.JRadioButton();
        Tomatonoodles = new javax.swing.JRadioButton();
        Rice = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ClientRole/Potato.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(314, 38, 200, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ClientRole/Broccoli.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(557, 38, 231, 166);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ClientRole/Tomatonoodles.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(79, 263, 223, 173);

        Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ClientRole/Rice.png"))); // NOI18N
        Label.setText("Label");
        getContentPane().add(Label);
        Label.setBounds(420, 280, 184, 148);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Trattatello", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 400, 110, 40);

        Fish.setText("Fish");
        getContentPane().add(Fish);
        Fish.setBounds(72, 222, 270, 23);

        Potato.setText("Potato");
        getContentPane().add(Potato);
        Potato.setBounds(310, 220, 72, 23);

        Broccoli.setText("Broccoli");
        getContentPane().add(Broccoli);
        Broccoli.setBounds(550, 220, 82, 23);

        Tomatonoodles.setText("Tomato noodles");
        getContentPane().add(Tomatonoodles);
        Tomatonoodles.setBounds(80, 440, 134, 23);

        Rice.setText("Rice");
        getContentPane().add(Rice);
        Rice.setBounds(420, 440, 58, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ClientRole/Fish.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 31, 208, 173);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Fish.isSelected()){
            foodDirectory.createFood("Fish");
//            enterprise.getFoodDirectory().addFood();
        }
//
        if(Potato.isSelected()){
            foodDirectory.createFood("Potato");
        }
//        }
////
       if(Broccoli.isSelected()){
           foodDirectory.createFood("Broccoli");
        }
////
        if(Tomatonoodles.isSelected()){
            foodDirectory.createFood("Tomato noodles");
        }
////
        if(Rice.isSelected()){
            foodDirectory.createFood("Rice");
        }

//        userProcessContainer = new RequestDietitionAdminOrSenateAdminTestJPanel(foodDirectory);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Broccoli;
    private javax.swing.JRadioButton Fish;
    private javax.swing.JLabel Label;
    private javax.swing.JRadioButton Potato;
    private javax.swing.JRadioButton Rice;
    private javax.swing.JRadioButton Tomatonoodles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
