/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Client.Client;
import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Food.FoodDirectory;
import userinterface.ClientRole.RequestDietitionAdminOrSenateAdminTestJPanel;
import java.io.File;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author leslie
 */
public class ViewClient extends javax.swing.JFrame {

    
    private Enterprise enterprise;
    private Client client;
    
    /**
     * Creates new form SendEmailJFrame
     */
    
    public ViewClient(Client client) {
        initComponents();
//        enterprise = enterprise;
         this.client =  client;
         popdetail();
       
    }
    public void popdetail(){
        ClientName.setText(client.getClientName());
        Age.setText(String.valueOf(client.getAge()));
        Height.setText(String.valueOf(client.getHeight()));
        Weight.setText(String.valueOf(client.getWeight()));
        BloodPressure.setText(String.valueOf(client.getBloodPressure()));
        Diease.setText(client.getDieaseName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Height = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Weight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BloodPressure = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ClientName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Diease = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel6.setText("Height /cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 120, 120, 20);

        Height.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        getContentPane().add(Height);
        Height.setBounds(120, 150, 141, 40);

        jLabel7.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel7.setText("Weight /kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 130, 120, 30);

        Weight.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightActionPerformed(evt);
            }
        });
        getContentPane().add(Weight);
        Weight.setBounds(700, 160, 160, 40);

        jLabel8.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel8.setText("Age");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(600, 30, 100, 40);

        Age.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        getContentPane().add(Age);
        Age.setBounds(640, 70, 170, 40);

        jLabel9.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel9.setText("Blood pressure /mmHg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 210, 240, 40);

        BloodPressure.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        BloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPressureActionPerformed(evt);
            }
        });
        getContentPane().add(BloodPressure);
        BloodPressure.setBounds(110, 260, 141, 40);

        jLabel10.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel10.setText("Client Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 30, 130, 30);

        ClientName.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        ClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientNameActionPerformed(evt);
            }
        });
        getContentPane().add(ClientName);
        ClientName.setBounds(150, 70, 141, 40);

        jLabel11.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        jLabel11.setText("Diease");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(660, 230, 90, 30);

        Diease.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        getContentPane().add(Diease);
        Diease.setBounds(700, 280, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/kissclipart-nursing-ratchaburi-hospital-nurse-35d267551b6948e5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void BloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPressureActionPerformed

    private void ClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientNameActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField BloodPressure;
    private javax.swing.JTextField ClientName;
    private javax.swing.JTextField Diease;
    private javax.swing.JTextField Height;
    private javax.swing.JTextField Weight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
