/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalalarmRole;

import Business.EcoSystem;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.SenateEnterprise;
import Business.Network.Network;
import Business.Organization.HospitalalarmOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HalarmTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bb
 */
public class HospitalalarmWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise HospitalEnterprise;
    private HospitalalarmOrganization hAlarmOrganization;
    private Network network;
    
    /**
     * Creates new form HospitalalarmWorkAreaJPanel
     */
    public HospitalalarmWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.hAlarmOrganization = (HospitalalarmOrganization)organization;
        this.HospitalEnterprise =(HospitalEnterprise) enterprise;
        network = searchNetwork();
        populateTable();
        populateRequestTable();
        
    }

    public Network searchNetwork(){
            for(Network network: business.getNetworkList()){
                if(network.getEnterpriseDirectory().getEnterpriseList().contains(HospitalEnterprise))
                    return network;
        }
            return null;
    }
    
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
       System.out.print(HospitalEnterprise.getWorkQueue().getWorkRequestList());
        for(WorkRequest request : HospitalEnterprise.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver();
            row[3] = request.getStatus();
            model.addRow(row);
        }
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel)RequestNurse.getModel();
        
        model.setRowCount(0);
//        if(userAccount!=null){
//            System.out.println(userAccount.getWorkQueue().getWorkRequestList());
//        }
        
        
        for(WorkRequest request : hAlarmOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            
            
            model.addRow(row);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RequestNurse = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        requestHospital = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 95, 410, 412);

        jLabel2.setFont(new java.awt.Font("PMingLiU", 1, 24)); // NOI18N
        jLabel2.setText("Request:");
        add(jLabel2);
        jLabel2.setBounds(20, 10, 152, 37);

        btnRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnRequest.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest);
        btnRequest.setBounds(210, 520, 170, 50);

        btnAssign.setBackground(new java.awt.Color(255, 255, 255));
        btnAssign.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign);
        btnAssign.setBounds(20, 520, 150, 50);

        jLabel1.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        jLabel1.setText("From Salarm");
        add(jLabel1);
        jLabel1.setBounds(20, 50, 180, 40);

        RequestNurse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(RequestNurse);

        add(jScrollPane2);
        jScrollPane2.setBounds(490, 90, 440, 412);

        assignJButton.setBackground(new java.awt.Color(255, 255, 255));
        assignJButton.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton);
        assignJButton.setBounds(490, 520, 210, 50);

        requestHospital.setBackground(new java.awt.Color(255, 255, 255));
        requestHospital.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        requestHospital.setText("Request ");
        requestHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestHospitalActionPerformed(evt);
            }
        });
        add(requestHospital);
        requestHospital.setBounds(710, 520, 200, 50);

        jLabel3.setFont(new java.awt.Font("Trattatello", 0, 24)); // NOI18N
        jLabel3.setText("From Nurse");
        add(jLabel3);
        jLabel3.setBounds(490, 60, 130, 28);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HospitalalarmRole/500_F_118386919_xzfTiT7e62SNwPI4prWKdDsQrH72Mu9A.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(210, 180, 740, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            HalarmTestWorkRequest request = (HalarmTestWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("HospitalalarmRequestNurseJPanel", new HospitalalarmRequestNurseJPanel(userProcessContainer, userAccount, hAlarmOrganization, HospitalEnterprise,request));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = RequestNurse.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)RequestNurse.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        //        populateTable();
        DefaultTableModel model = (DefaultTableModel)RequestNurse.getModel();

        model.setRowCount(0);
        //        if(userAccount!=null){
            //            System.out.println(userAccount.getWorkQueue().getWorkRequestList());
            //        }

        for(WorkRequest c : hAlarmOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = c;
            row[1] = c.getSender().getEmployee().getName();
            row[2] = c.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = c.getStatus();

            model.addRow(row);
        }
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void requestHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestHospitalActionPerformed
        // TODO add your handling code here:
        int selectedRow = RequestNurse.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest request = (WorkRequest)RequestNurse.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Processed")){
            JOptionPane.showMessageDialog(null, "This Request has been processed!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
//        System.out.println(network.getEnterpriseDirectory().getEnterpriseList());
        //        String suppliername = String.valueOf(ComboBox.getSelectedItem());
        SenateEnterprise senateEnterprise =null;

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if (enterprise instanceof SenateEnterprise ){
                senateEnterprise = (SenateEnterprise)enterprise;
                senateEnterprise.getWorkQueue().getWorkRequestList().add(request);
                //                System.out.println(hospitalEnterprise.getWorkQueue().getWorkRequestList());
            }
        }

    }//GEN-LAST:event_requestHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestNurse;
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton requestHospital;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
