/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalalarmRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.HospitalalarmOrganization;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HalarmTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bb
 */
public class HospitalalarmRequestNurseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise HospitalEnterprise;
    private HospitalalarmOrganization hAlarmOrganization;
    private EmployeeDirectory nurseDir;
    private HalarmTestWorkRequest request;
    
    
    /**
     * Creates new form HospitalalarmRequestNurseJPanel
     */
    public HospitalalarmRequestNurseJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, HalarmTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.hAlarmOrganization = (HospitalalarmOrganization)organization;
        this.HospitalEnterprise = enterprise;
        this.request = request;
        //nurseDir = HospitalEnterprise.getOrganizationDirectory();
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        System.out.print(HospitalEnterprise.getOrganizationDirectory().getOrganizationList().toString());
        for(int i=0; i<HospitalEnterprise.getOrganizationDirectory().getOrganizationList().size(); i++){
            if(HospitalEnterprise.getOrganizationDirectory().getOrganizationList().get(i).toString().equals("Nurse Organization")){
                nurseDir = HospitalEnterprise.getOrganizationDirectory().getOrganizationList().get(i).getEmployeeDirectory();
            }
        }
        
//        System.out.print(nurseDir.getEmployeeList().toString());
        for(Employee nurse : nurseDir.getEmployeeList()){
            Object[] row = new Object[3];
            row[0] = nurse;
            row[1] = nurse.getId();
            row[2] = nurse.isAvailability();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("PMingLiU", 1, 24)); // NOI18N
        jLabel1.setText("Nurse:");
        add(jLabel1);
        jLabel1.setBounds(129, 46, 152, 37);

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nurse_name", "Id", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(120, 115, 454, 185);

        btnRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnRequest.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest);
        btnRequest.setBounds(380, 350, 190, 50);

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Silom", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(120, 350, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HospitalalarmRole/500_F_118386919_xzfTiT7e62SNwPI4prWKdDsQrH72Mu9A.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(410, 10, 430, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
//        System.out.print(workRequestJTable.getValueAt(selectedRow,0));
        Employee selected_nurse = (Employee)workRequestJTable.getValueAt(selectedRow,0);
        UserAccount nurse_account = new UserAccount();
        nurse_account.setUsername(selected_nurse.getName());
        nurse_account.setEmployee(selected_nurse);
//        System.out.print(selected_nurse.getName());
        request.setNurse_toSend(nurse_account);
        request.setReceiver(userAccount);
        request.setStatus("need nurse");
//        System.out.print(request.getNurse_toSend().getEmployee().getName());
    }//GEN-LAST:event_btnRequestActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
